# Generated by Django 3.2 on 2022-09-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='docs',
            name='name',
        ),
        migrations.AddField(
            model_name='docs',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
