# Generated by Django 3.2 on 2022-09-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220913_0225'),
        ('shift', '0002_auto_20220913_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='shift_ass',
        ),
        migrations.AddField(
            model_name='notifications',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.homeprofile'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shiftname'),
        ),
        migrations.DeleteModel(
            name='HomeNotifications',
        ),
    ]
